package game;

public enum GameState {
    STARTING,
    CHOOSING_MAIN_MENU_OPTION,
    QUITTING,
    HELPING,
    PC_VS_PC,
    PLAYING_AGAINST_PC,
    CHOOSING_TO_PLAY_FIRST,
    PLAYER_1_PLAYING,
    PLAYER_2_PLAYING,
    FINISHING_GAME
}
